[package]
name = "magnus"
version = "0.1.0"
authors = ["Mat Sadler <mat@sourcetagsandcodes.com>"]
edition = "2018"
description = "Ruby bindings for Rust."

[workspace]
members = ["magnus-macros"]

[dependencies]
magnus-macros = { path = "magnus-macros" }

[build-dependencies]
bindgen = "0.58"
