[package]
name = "rust_blank"
version = "0.2.0"
authors = ["Mat Sadler <mat@sourcetagsandcodes.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { path = "../../../..", features = ["rb-sys-interop"] }
rb-sys = { version = "0.9.9", features = ["gem"] }
