name: Test

on:
- push
- pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        ruby-version:
        - "2.6"
        - "2.7"
        - "3.0"
        - "3.1"
        exclude:
        # environment for Ruby 3.1 on Windows is messed up
        - os: windows-latest
          ruby-version: "3.1"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Set up Rust
      if: matrix.os == 'windows-latest'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-pc-windows-gnu
        default: true
    - name: Set LD_LIBRARY_PATH
      if: matrix.os == 'ubuntu-latest'
      run: echo LD_LIBRARY_PATH=$(ruby -e 'print RbConfig::CONFIG["libdir"]') >> $GITHUB_ENV
    - name: Run tests
      run: cargo test
